- argocd/provider.go
- argocd/provider_test.go
- main.go
Closes #23
Workaround for apiclients closure race condition, needs more future work to properly wait for all provider activity to end before closing those.
> removed explicit shared apiclients closing

- argocd/resource_argocd_application.go
- argocd/resource_argocd_project.go
- argocd/resource_argocd_repository.go
- argocd/resource_argocd_repository_credentials.go
> Handle absent resources upon deletion, force argocd_repository connection cache refreshes upon reads

- .github/workflows/tests.yml
- .run/Template Go Test.run.xml
- README.md
- argocd/resource_argocd_application_test.go
- argocd/resource_argocd_repository_test.go
- manifests/install/kustomization.yml
- manifests/install/proxy-service.yml
- scripts/kind-config.yml
- scripts/testacc_prepare_env.sh
* persisted Goland gotest templates
* made Kind test settings cross-platform through extraPortMappings
* removed CI testing dependencies with kubectl proxy
* side-loads local container registry images into Kind during cluster initialization
* updated Github Actions accordingly
* fixed Kustomize tests, targeting kubernetes-sigs/kustomize release-kustomize-3.7 branch instead of master (breaking changes introduced within Kustomize examples)
closes #41
> Portable, cross-platform tests settings

- .github/workflows/tests.yml
- README.md
- argocd/resource_argocd_project.go
- argocd/resource_argocd_project_test.go
- argocd/schema_project.go
- argocd/structure_project.go
- docs/resources/project.md
**BREAKING CHANGES**:
argocd_project.spec.0.orphaned_resources attribute has been changed from a map to a set of map.
From
```hcl
orphaned_resources = {
warn = true
}
```
To
```hcl
orphaned_resources {
warn = true
}
```
Closes #49 
**BUGFIX:**
Fix project updates when adding new project roles. (Closes #51 )
> argocd_project: handles orphaned_resources/ignore, signature_keys

- README.md
- argocd/resource_argocd_application.go
- argocd/resource_argocd_application_test.go
- argocd/schema_application.go
- docs/resources/application.md
- go.mod
- scripts/testacc_prepare_env.sh
> argocd_application: introduce wait parameter

- argocd/structure_metadata.go
- argocd/structure_metadata_test.go
Hi,
I use [Argo CD Notifications](https://argocd-notifications.readthedocs.io/en/stable/) which store dynamically some datas into an annotation named : **notified.notifications.argoproj.io**.
Example : 
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
annotations:
notifications.argoproj.io/subscribe.on-created.grafana: platform-created
notified.notifications.argoproj.io: '{"my-app-dev1:on-created:[0].Y_9K23NSHEAsZ2kqeSw2_KxnMps:grafana:argocd":1618503285,"my-app-dev1:on-created:[0].Y_9K23NSHEAsZ2kqeSw2_KxnMps:grafana:platform-created":1618503285,"my-app-dev1:on-created:[0].Y_9K23NSHEAsZ2kqeSw2_KxnMps:teams:my-team":1618503284}'
creationTimestamp: "2021-04-15T16:14:44Z"`
```
I have change each time i run terraform ...
Could you implement this little feature ?
In accordance …
> ignore notified.notifications.argoproj.io annotations

- argocd/provider.go
- docs/index.md
Cfr. argocd docs on running argocd at a different UI root path: [ArgoCD Server and UI Root Path (v1.5.3)](https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#argocd-server-and-ui-root-path-v153)
> Add support for GRPCWebRootPath ArgoCD ApiClient ClientOption

- README.md
- argocd/resource_argocd_project_test.go
- argocd/schema_project.go
- argocd/schema_project_test.go
- argocd/structure_project.go
- docs/resources/project.md
- manifests/local-dev/main.tf
Currently this provider only supports NamespaceResourceBlacklist and ClusterResourceWhitelist for projects.
This PR adds support for NamespaceResourceWhitelist and ClusterResourceBlacklist to make these options complete and in line with what ArgoCD supports.
> Add support for NamespaceResourceWhitelist and ClusterResourceBlacklist

- argocd/resource_argocd_repository_credentials_test.go
- argocd/resource_argocd_repository_test.go
Arguably, this seems to be a regression in Argo CD itself, so it should probably be forwarded there, but at least this fixes the tests for the provider.
Signed-off-by: Raphaël Pinson <raphael.pinson@camptocamp.com>
> fix(tests): use ssh:// in TestAccArgoCDRepositoryCredentials

- .github/workflows/tests.yml
- README.md
To ensure that the provider works with the current version. Version 2.2.5 is added without any older versions being removed increasing the workflows executed. As per #141 I found it unclear which versions the provider should maintain compatibility with.
> tests: add argocd 2.2.5 to test suite

- .github/workflows/tests.yml
- argocd/features.go
- argocd/provider_test.go
- argocd/resource_argocd_cluster.go
- argocd/resource_argocd_cluster_test.go
- argocd/schema_cluster.go
- argocd/structure_cluster.go
- docs/resources/cluster.md
Adds support for project scoped clusters: https://argo-cd.readthedocs.io/en/stable/user-guide/projects/#project-scoped-repositories-and-clusters
I'm deliberately adding an acceptance tests that breaks with 2.1.0 because that version does not have support for scoped clusters, any ideas on how to deal with tests that require at least some version of argocd? I'm thinking if adding a precheck function to check the argocd version and skip if it is not compatible could be a good solution?
> add: project scope support for clusters

- argocd/structure_cluster.go
The types are `[]interface{}` and `map[string]interface{}`, so they need to be converted item-by-item.
> Handle expanding types of exec_provider_config args and env properly

- argocd/features.go
- argocd/resource_argocd_cluster.go
- argocd/resource_argocd_cluster_test.go
- argocd/structure_cluster.go
Looks like cluster metadata is not read and does not import properly in the current release.
In addition to fixing that issue this also adds an acceptance and version constraint for cluster metadata.
> Improve cluster metadata support

- argocd/resource_argocd_project_test.go
- argocd/structure_project.go
Resolves #105 & #104 
To be on par with the API surface of Argo CD, "orphaned resources monitoring" will be only enabled if it is explicitly declared. Monitoring enabled because of the previous default behavior will be detected as a removal on next apply.
This is a **BREAKING CHANGE** with the current version :
<table>
<tr>
<td>"Orphaned resources" block specified
<td> Current version
<td> This PR
<tr>
<td> Yes
<td> Enables monitoring
<td> Enables monitoring
<tr>
<td> No
<td> Enables monitoring
<td> Disables monitoring
</table>
> fix: constant orphaned changes if not specified & crash

- argocd/provider.go
Fixes #151 (cf https://github.com/kubernetes/client-go/blob/37ed584bedcad175bc0af93c02c356e4998dbeb9/tools/clientcmd/api/types.go#L249-L259)
> fix(auth): allow interactive auth with k8s block

- argocd/resource_argocd_application_test.go
- argocd/schema_application.go
Make argocd_application.revision_history_limit default value to 10, as stated by documentation (fixes #160)
`(Optional) This limits the number of items kept in the apps revision history. This should only be changed in exceptional circumstances. Setting to zero will store no history. This will reduce storage used. Increasing will increase the space used to store the history, so we do not recommend increasing it. Default is 10.`
> fix: wrong default value for revision_history_limit in argocd_application resource

- docs/resources/cluster.md
Following the "[Example Usage - GCP GKE cluster](https://registry.terraform.io/providers/oboukili/argocd/latest/docs/resources/cluster#example-usage---gcp-gke-cluster)" guide cluster creation kept failing, Comparing clusters created through the provider with existing clusters showed that the bearer_token config was missing. 
I'm thinking its a mistake since the kubernetes_secret data source is already in the example but unused. 
If for some reason this is by design, or i missed some "before you make PR's here please read and do this and that section" i apologize and the PR can be closed.
> docs: add missing bearer_token config

- argocd/provider.go
- argocd/resource_argocd_cluster.go
- argocd/resource_argocd_cluster_test.go
- argocd/schema_cluster.go
* Name was already an optional property (defaulted to `server`) but made a weird `ID` = `server/name` (ex: https://kubernetes.default.svc.cluster.local/https://kubernetes.default.svc.cluster.local) which broke the ID parser on read and made further operations impossible.
Should fixes parts of #84 
* I also noticed while testing clusters that if you declare 2 clusters with the same server adress, they will manage the same item on k8s and overwrite each other properties (since we have `upsert: true`). 
I made a few tests on the REST api to make sure I got the same results :
```json
{
"config": {
"bearerToken": "abcdef.0123456789abcdef",
"tlsClientConfig": { "insecure": true }
},
"name": "hello",
"server": "https://kubernetes.default.svc.cluster.local"
}
```
POST => 200 OK
```diff
{ …
```
> fix: Allow cluster name to be omitted & ensure unique cluster on creation

- argocd/resource_argocd_application_test.go
- argocd/schema_application.go
Add "." as default path in argocd_application .spec.source so it is properly optional
Fixes #97
> fix: default path "." is not defined in argocd_application

- argocd/features.go
- argocd/provider.go
- argocd/resource_argocd_repository.go
- argocd/resource_argocd_repository_certificates.go
- argocd/resource_argocd_repository_certificates_test.go
- argocd/schema_repository_certificates.go
- argocd/structure_repository_certificate.go
- argocd/validators.go
- docs/resources/repository_certificate.md
Resolves #56 
Implements ssh & https certificates as `argocd_repository_certificate` resource :
* only on server > 1.2.0
* there is no update API, so I didn't make a resourceUpdate
* upstream api has some weird behaviors, so weird workarounds like
https://github.com/MrLuje/terraform-provider-argocd/blob/ee042d95bb4572939961c9b8760fd7d397903e09/argocd/resource_argocd_repository_certificates.go#L124-L132
* not sure why but I had a `create` drift, since the API is not returning the cert_data, it was always reported as an addition
I had no bug with my initial implementation as a flat map but it doesn't work correctly with `ssh`/`https` as a list, so I used context to make it through
https://github.com/MrLuje/terraform-provider-argocd/blob/ee042d95bb4572939961c9b8760fd7d397903e09/argocd/resourc …
> feat: add resource argocd_repository_certificate 

- .github/workflows/tests.yml
- argocd/features.go
- argocd/provider_test.go
- argocd/resource_argocd_application.go
- argocd/resource_argocd_application_test.go
- argocd/resource_argocd_cluster.go
- argocd/resource_argocd_cluster_test.go
- argocd/resource_argocd_project.go
- argocd/resource_argocd_project_test.go
- argocd/resource_argocd_repository.go
- argocd/resource_argocd_repository_credentials.go
- argocd/resource_argocd_repository_credentials_test.go
- argocd/resource_argocd_repository_test.go
- argocd/schema_application.go
- argocd/schema_application_test.go
- argocd/structure_application.go
- docs/resources/application.md
- scripts/testacc.sh
* added **skip_crds** to helm in `argocd_application` (Resolves #166)
```hcl diff
resource "argocd_application" "crds" {
metadata {
...
}
spec {
source {
repo_url        = "https://charts.bitnami.com/bitnami"
chart           = "redis"
target_revision = "15.3.0"
helm {
release_name = "testing"
+		  skip_crds = true
}
}
destination {
server    = "https://kubernetes.default.svc"
namespace = "default"
}
}
}
```
* added a StateUpgrader to add the default value (false)
* added a bunch of ResourceImporter tests
> feat(application): add SkipCrds to helm source

- argocd/resource_argocd_cluster_test.go
- argocd/structure_cluster.go
Fix a crash when `cluster.namespaces` contains empty string
```hcl
resource "argocd_cluster" "simple" {
server = "https://kubernetes.default.svc.cluster.local"
name   = "%s"
shard  = "1"
namespaces = [""]
config {
bearer_token = "abcdef.0123456789abcdef"
tls_client_config {
insecure = true
}
}
}
```
Documentation for namespaces is : 
> Holds list of namespaces which are accessible in that cluster. Cluster level resources will be ignored if namespace list is not empty.
So, nil item in `namespaces` makes no sense
Resolves #197
> fix(cluster): crash on empty namespace

- go.mod
- go.sum
When I was trying to run the tests locally, they were failing to compile on master. Why? I am on a Mac M1 / Arm64 computer. One of the transitive dependencies, bigftt, [is five years old](https://github.com/remyoudompheng/bigfft/tree/52369c62f4463a21c8ff8531194c5526322b8521) and lacks arm64 support. Using a replace to get a newer version does allow me to run the tests.
If you are curious about the error:
```
make testacc_prepare_env && make testacc && make testacc_clean_env
....                                               
sh scripts/testacc.sh
../../../../pkg/mod/github.com/remyoudompheng/bigfft@v0.0.0-20170806203942-52369c62f446/arith_decl.go:10:6: missing function body
../../../../pkg/mod/github.com/remyoudompheng/bigfft@v0.0.0-20170806203942-52369c62f446/arith_decl.go:11:6: missing …
```
> Get tests working on M1/ARM 64

- README.md
I was wanting to contribute.
While following the readme to run the tests, I noticed that the tests fail because I didn't not have Kustomize installed. I've updated the README accordingly on this PR.
Another issue I found, while combing the readme, was that the status badge wasn't working. I think I fixed it to what it is meant to show.
> Readme fix: badge update and kustomize is needed to run tests

- argocd/resource_argocd_application_test.go
- argocd/schema_application_test.go
Bitnami regularly prunes their helm repo. Every once in a while, they prune any charts older than six months. The chart being used for tests (v16.9.11) got pruned in the last few days.
Bitnami keeps a full-index copy in git. This PR swaps to that full-index.
https://github.com/bitnami/charts/issues/10833 for details.
> Fetch bitnami charts from full-index repo

- argocd/resource_argocd_repository.go
- argocd/resource_argocd_repository_credentials.go
- argocd/resource_argocd_repository_credentials_test.go
- argocd/resource_argocd_repository_test.go
- argocd/schema_repository.go
- argocd/schema_repository_credentials.go
- argocd/structure_repository.go
- argocd/structure_repository_credentials.go
- argocd/validators.go
- docs/resources/repository.md
- docs/resources/repository_credentials.md
We need to switch our authentication towards github to GitHub App. As there was also a feature request for this one in the issues, I hence added GitHub App functionality to the following ressources:
- argocd_repository
- argocd_respository_credentials
The underlying package already [supports](https://pkg.go.dev/github.com/argoproj/argo-cd/v2/pkg/apis/application/v1alpha1#RepoCreds) it
> Add support for GitHub app credentials

- argocd/schema_application.go
- argocd/schema_application_test.go
- main.go
Fixes state upgrade/migration for `argocd_application` resources in `v5.0.0`.
Also ensures plugin can be run in "debug" mode (kudos to https://opencredo.com/blogs/running-a-terraform-provider-with-a-debugger/ for the technique) - which, allowed me to be able to debug the issue and test this fix.
Closes #236
> Fix `argocd_application` state upgrade for `v5.0.0`

- argocd/resource_argocd_application.go
- docs/resources/application.md
Adds a check on `ReconciledAt` when _waiting_ on application update, ensuring that the update has been processed by ArgoCD (at which point health/sync status will be updated). Note, the update to `ReconciledAt` will occur even if ArgoCD decides not to sync the application (e.g. if a project `sync_window` prevents this). In this scenario, Terraform will eventually timeout with the following error:
``` 
╷
│ Error: something went wrong upon waiting for the application to be updated: expected application sync status to be synced but was OutOfSync
│ 
│   with argocd_application.foo,
│   on application.tf line 1, in resource "argocd_application" "foo":
│    1: resource "argocd_application" "foo" {
│ 
│ expected application sync status to be synced but was OutOfSync
╵
```
Fixes #110
> Fix `wait` on update of `argocd_application`

- argocd/resource_argocd_application_test.go
- argocd/schema_application.go
- argocd/structure_application.go
- docs/resources/application.md
Closes #208
Notes:
- Feature was introduced prior to `v2.0.0`, so it is available across all versions supported by the provider (hence, no feature/version testing).
> Add support for `include` and `exclude` on directory apps

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/question.md
Adds issue templates to this repository to try and improve the _quality_ of any issues that are opened (thereby making them easier to respond to). Templates have been (largely) taken from https://github.com/hashicorp/terraform-provider-kubernetes/tree/main/.github/ISSUE_TEMPLATE
> Add issue templates

- .github/ISSUE_TEMPLATE/feature-request.md
The template currently isn't showing up in "New Issue" due to issues with metadata/header section that were introduced when I was editing #259 :see_no_evil:
> Fix "Feature Request" issue template

- argocd/resource_argocd_project_test.go
- argocd/validators.go
For reference, see [project.yaml](https://argo-cd.readthedocs.io/en/stable/operator-manual/project.yaml), which gives examples of using a blank group for various resources.
Closes #257
> Allow blank `Group` on cluster resource [white|black]list

- argocd/resource_argocd_cluster.go
- argocd/resource_argocd_cluster_test.go
This PR aims to address the currently flaky invalid cluster tests in a less _invasive_ manner than #263, which requires further thought with regard to the performance implications. 
When looking at this in more detail, I identified 3 separate issues that resulted in these tests being flaky.
- We shouldn't be testing whether attributes are set on tests that are designed to return errors. This is because the order in which the "duplicate" resources are applied is non-deterministic, and so sometimes resource 1 gets applied, and resource 2 causes the error, and other times it is the other way around. Thus we end up with errors such as:
``` 
resource_argocd_cluster_test.go:343: Step 1/1, expected an error with pattern, no match on: Check failed: Check 3/3 error: argocd_cluster.cluster_one: …
```
> Prevent duplicate clusters ending up in Terraform state

- argocd/features.go
- argocd/resource_argocd_application.go
- argocd/resource_argocd_cluster.go
- argocd/resource_argocd_project.go
- argocd/resource_argocd_project_token.go
- argocd/resource_argocd_repository.go
- argocd/resource_argocd_repository_certificate.go
- argocd/resource_argocd_repository_credentials.go
"Cherry picking" this change out of #263 so that that implementation becomes a little cleaner. 
Ultimately the pointers to the `XClient` objects are unnecessary and just end up being dereferenced when we want to use them.
> Drop use of pointers on clients

- argocd/resource_argocd_application_test.go
- argocd/schema_application.go
- argocd/structure_application.go
- docs/resources/application.md
> add pass_credentials to helm source

- argocd/resource_argocd_project.go
- argocd/resource_argocd_project_token.go
- argocd/resource_argocd_project_token_test.go
- argocd/resource_argocd_repository.go
~This PR addresses the flaky cluster tests by fixing the locking mechanism used to control the concurrent provisioning of resources via the provider. The existing mechanism is flawed in that locks are only maintained for individual calls to the API, thereby allowing cases where for example:~
~- a delete may occur in the middle of the update of an existing resource~
~- two creates of identical resources may run at the same time leading to a plan diff~
~Examples of both can be seen in the logs [here](https://github.com/oboukili/terraform-provider-argocd/actions/runs/4789891646/jobs/8519015272).~
~The change in this PR ensures that a single lock is maintained for the full Terraform CRUD action (and all API calls required to complete it). Also, since the same locking pattern is used across a …
> Fix locking on resources during Terraform actions

- .github/workflows/stale.yml
Updates settings on `actions/stale` GitHub action to also label issues labelled as `cannot-reproduce` or `needs-more-info` as `Stale` (after 14 days) and to automatically close them 10 days after being labelled as `Stale`.
> Automatically close stale issues

- .github/workflows/tests.yml
- argocd/resource_argocd_application.go
- argocd/structure_application_set.go
A few folks are having issues with the `argocd_application` resource since we introduced support for multiple application sources in #262. While one could argue that these issues are not really the fault of the provider, this is still a beta feature within ArgoCD, and we can also mitigate the problems by ensuring that we only make use of `Sources` (when creating/updating applications) for applications that do have multiple sources defined. 
Closes #274 
Closes #288
> Populate `Source` not `Sources` for single source applications

- argocd/features.go
- argocd/features_test.go
- argocd/provider_test.go
- argocd/resource_argocd_account_token.go
- argocd/resource_argocd_application.go
- argocd/resource_argocd_application_set.go
- argocd/resource_argocd_application_set_test.go
- argocd/resource_argocd_application_test.go
- argocd/resource_argocd_cluster.go
- argocd/resource_argocd_cluster_test.go
- argocd/resource_argocd_project.go
- argocd/resource_argocd_project_test.go
- argocd/resource_argocd_project_token.go
- argocd/resource_argocd_repository.go
- argocd/resource_argocd_repository_certificate.go
- argocd/resource_argocd_repository_credentials.go
- argocd/resource_argocd_repository_test.go
- argocd/server.go
- argocd/server_test.go
- argocd/structure_application_set.go
- argocd/structure_repository_credentials.go
- argocd/utils.go
- go.mod
- go.sum
- internal/features/features.go
Simplifies error handling across all resources through the introduction of 3 utils methods (see related discussion [here](https://github.com/oboukili/terraform-provider-argocd/pull/278#discussion_r1204744146)):
- `featureNotSupported` - used to simplify error returned if a user makes use of configuration options that are not supported by their ArgoCD version
- `argoCDAPIError` - used to standardise error messages returned by the provider when handling errors returned by the ArgoCD API during CRUD operations
- `errorToDiagnostics` - provides a terser syntax to return an error message (and detail) when handling errors
**Note**: as part of this change, we are explicitly dropping feature "flags" for all unsupported versions of ArgoCD. In most cases, this won't affect consumers since, if they …
> Refactor error handling

- argocd/resource_argocd_project_token.go
Fixes an (unreleased) regression introduced in #291 by ensuring that we set that `Id` when deleting project tokens.
> fix(project_token): ensure correct token is deleted

- .github/workflows/tests.yml
- argocd/structure_repository.go
Closes #270
Dependent on https://github.com/argoproj/argo-cd/pull/13428, which will be contained in the next set of patch releases for `2.5.x`->`2.7.x` (due for release shortly). Once this happens, I will bump the build/test versions, which should resolve the current failures. Similarly, consumers will need to update to those patches to prevent the same perma-diff being introduced on `username` due to this change.
> Prevent permanent diff on `argocd_repository` with inherited credentials

- argocd/resource_argocd_cluster_test.go
- argocd/schema_cluster.go
- argocd/structure_cluster.go
- docs/resources/cluster.md
This change ensures that the `argocd_cluster` resource won't perma-diff on sensitive attributes whilst, at the same time, ensuring that we track the remote state for non-sensitive attributes that are returned by the API (see comment inline). 
Closes #297
> Prevent permanent diff on `argocd_cluster` with sensitive attributes

- argocd/resource_argocd_account_token_test.go
- argocd/resource_argocd_cluster_test.go
- argocd/resource_argocd_project_test.go
- argocd/resource_argocd_project_token_test.go
- argocd/schema_project.go
- argocd/structure_application.go
- argocd/structures.go
- argocd/validators.go
- docs/resources/project.md
- examples/resources/argocd_project/resource.tf
- manifests/local-dev/project.tf
Whilst the ArgoCD API now supports setting the timezone in a project's sync window, the provider does not expose this so I have had to set it manually. This change exposes the timezone capability in the provider so that it can be configured via Terraform.
> Add support for timezone in sync window

- argocd/structure_cluster.go
There is no need to cast the attributes we "load" from the existing state when flattening. Instead, we can simply set the flattened state using whatever we loaded from the existing state. 
Closes #306
> fix(cluster): don't cast attributes when loading from state

- internal/provider/model_provider.go
> Ensure `use_local_config` is correctly applied and validated

- argocd/schema_label_selector.go
Fixes [(#330)](https://github.com/oboukili/terraform-provider-argocd/issues/330).
This PR removes `ForceNew: true` from the `matchExpressionsSchema()` allowing match expressions to be added and removed without destroying the argocd_application_Set resource.
After making the changes, I see a handful of tests failing. Some, like `TestAccArgoCDRepositoryCertificatesSSH_WithApplication`, `TestAccArgoCDRepositoryCredentials`, and `TestAccArgoCDApplicationSet_matrixInvalid` fail even without the changes in this PR.  `TestAccArgoCDApplicationSet_mergeInvalid` and `TestAccArgoCDApplicationSet_generatorTemplate` begin failing once `ForceNew: true` is removed and I can't seem to figure out how they are connected to`matchExpressionsSchema()`. 
Here are the test failures:
--- The first two tests only …
> Don't force new `argocd_application_set` resource when adding/removing `match_expressions`

- argocd/structure_application.go
Fixes #277
Seems to be an edge case of:
- #168
/cc: @onematchfox , @MrLuje
> fix(argocd_application): don't flatten `spec.info` if list is empty

- argocd/schema_cluster.go
While working on this PR here:
- #349
, I saw that the build is already broken on `master` branch:
It seems that the test is failing due to inconsistent handling of a trailing `/`.
```log
=== RUN   TestAccArgoCDCluster_invalidSameServer
resource_argocd_cluster_test.go:275: Step 3/3, expected an error with pattern, no match on: After applying this test step, the plan was not empty.
stdout:
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place
Terraform will perform the following actions:
~ resource "argocd_cluster" "cluster_with_trailing_slash" {
id     = "https://kubernetes.default.svc.cluster.local/server"
name   = "server"
~ server = "https://kubernetes.default.svc.cluster.local/" -> …
```
> fix: Add DiffSuppressFunc on argocd_cluster.server

- .github/workflows/release.yml
- .github/workflows/tests.yml
Still fighting to unblock releases of this repository :weary: 
`release` workflow was explicitly using go version `1.19` which is causing the pipeline to [fail](https://github.com/oboukili/terraform-provider-argocd/actions/runs/8403053068/job/23013137436) as we now require [go `1.20`](https://github.com/oboukili/terraform-provider-argocd/blob/ea02a51e1ec7cfceb36ec2e89baadeebef51e546/go.mod#L3). 
Other version bumps resolve [deprecation warnings](https://github.com/oboukili/terraform-provider-argocd/actions/runs/8402768584) due to use of Node 16.x.
> Fix go version in release workflow and bump step versions

- internal/provider/model_provider.go
Configuring the provider with port forwarding is currently broken in `v6.1.0` due to changes introduced in https://github.com/argoproj/argo-cd/pull/14605. That PR introduced the requirement to set both `ServerName` and `PortForwardNamespace` when making use of port forwarding.
At present, `v6.1.0` will fail with the following error as we are not setting these values.
```
╷
│ Error: failed to create new API client
│ 
│   with argocd_repository.this,
│   on repository.tf line 1, in resource "argocd_repository" "this":
│    1: resource "argocd_repository" "this" {
│ 
│ cannot find pod with selector: [app.kubernetes.io/name=] - use the --{component}-name flag in this command or set the environmental variable (Refer to
│ https://argo-cd.readthedocs.io/en/stable/user-guide/environment-variables) …
```
> fix(provider): ensure `ServerName` and `PortForwardNamespace` are set on `ClientOptions` when port forwarding

- argocd/resource_argocd_application_set_test.go
- argocd/schema_application_set.go
- argocd/structure_application_set.go
- docs/resources/application_set.md
- add missing `values` field to to application_set [git generators](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Git/#pass-additional-key-value-pairs-via-values-field_1)
- mostly based on the same implementation as used for cluster generators
- add missing `go_template_options` field to application_set [spec](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/applicationset-specification/)
> feat: add applicationset git values

- argocd/resource_argocd_application.go
- argocd/resource_argocd_application_test.go
- docs/resources/application.md
resolves https://github.com/argoproj-labs/terraform-provider-argocd/issues/261
this PR adds `validate` (similar to `--validate` flag in argocd CLI) to `argocd_application` resource, to be able to skip(set it to false) the app validation. It is set to true by default.
> feat: add support for `validate` option when provisioning/maintaining argocd applications

- argocd/resource_argocd_application_test.go
- argocd/schema_application.go
- argocd/structure_application.go
- docs/resources/application.md
- docs/resources/application_set.md
> Added support for managedFieldsManagers and Helm templating version

- .goreleaser.yml
See failed Release action:
https://github.com/argoproj-labs/terraform-provider-argocd/actions/runs/11121825140/job/30901785438
> ```log
>       • upload failed                                request-id=3802:30B880:DCF2EC:EE58D2:66FBBA21 error=POST https://uploads.github.com/repos/oboukili/terraform-provider-argocd/releases/177753143/assets?name=terraform-provider-argocd_6.2.0_windows_amd64.zip: 307 Moved Permanently [] name=terraform-provider-argocd_6.2.0_windows_amd64.zip release-id=177753143
>       • failed to upload artifact, will retry        try=1 artifact=terraform-provider-argocd_6.2.0_windows_amd64.zip error=POST https://uploads.github.com/repos/oboukili/terraform-provider-argocd/releases/177753143/assets?name=terraform-provider-argocd_6.2.0_windows_amd64.zip: 307 Moved …
```
> ci: Fix GoReleaser config after repo move

- .github/workflows/stale.yml
Details:
- Reduce permissions of the GITHUB_TOKEN variable
- Action update v8 -> v9
- Increase stale days 14 -> 60
- Do not stale issues with labels "on-hold", "pinned" or "good first issue"
> chore: Update stale config

- .github/dependabot.yml
Until today we only activated dependabot in the repo settings but we did not add a config file for this bot.
Lets add a basic config file for `Go` and `github-actions`.
> chore: Configure dependabot explicitly

- .github/workflows/release.yml
- .goreleaser.yml
Our current GPG key did not have a passphrase. The current HashiCorp scaffolding uses the passphrase, so I updated to the latest scaffolding/examples of Hashi:
https://github.com/hashicorp/terraform-provider-scaffolding-framework/blob/main/.goreleaser.yml
I validated the new config using:
```bash
$ goreleaser -v
____       ____      _
/ ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
\____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com
GitVersion:    2.3.2
GitCommit:     e8c2ef77358b4b1e59b904322824ccbfa3487ab2
GitTreeState:  false
BuildDate:     2024-09-17T12:30:49Z
BuiltBy:       goreleaser
GoVersion: …
```
> chore: Prepare to sign with new GPG key (argoproj-labs)

- .github/workflows/tests.yml
Last workflow where actions used are not pinned
> chore: Bump golangci-lint-action v4 -> v6 and pin all other actions

- internal/provider/data_source_application_test.go
Fixes failing acceptance tests in (draft) PR over here:
- #438
> test: Make acceptance tests happy again

- go.mod
- go.sum
- internal/provider/server_interface.go
This replaces `github.com/golang/protobuf` with it's superseeded `google.golang.org/protobuf` module.
See [github.com/golang/protobuf's README](https://github.com/golang/protobuf) for the notice that this has moved to a new location.
Will hopefully make it easier to work on #445 as there are a lot of changes we need to reflect before we can bump the argo-cd module.
> feat: replace protobuf with new module

- .devcontainer.json
This adds a `devcontainer.json` file to the repo declaring as code the development environment needed to develop this provider. See [containers.dev](https://containers.dev) for the standard.
Helpful for users who want to quickly get started developing (e.g with Github Codespaces) or for users who like to offload their development workload to another machine using something like [devpod](https://devpod.sh).
I tested the image and did some coding using devpod, works like a charm. Might need slight updates in the future but I think It's a good v1 to work with.
> feat: add devcontainer

- .golangci.yml
This PR fixes these deprecation warnings:
```bash
$ golangci-lint-1.59.1 run
WARN [config_reader] The configuration option `linters.errcheck.ignore` is deprecated, please use `linters.errcheck.exclude-functions`.
WARN [config_reader] The configuration option `linters.gomnd.settings` is deprecated. Please use the options `linters.gomnd.checks`,`linters.gomnd.ignored-numbers`,`linters.gomnd.ignored-files`,`linters.gomnd.ignored-functions`.
WARN [lintersdb] The name "vet" is deprecated. The linter has been renamed to: govet.
WARN [lintersdb] The name "vetshadow" is deprecated. The linter has been renamed to: govet.
WARN The linter 'gomnd' is deprecated (since v1.58.0) due to: The linter has been renamed. Replaced by mnd.
```
**Note for reviewers:**
- Disable whitespace diff :)
> …
> ci: Fix deprecation warnings of golangci-lint

- .github/workflows/tests.yml
Fixes the CI tests which are currently failing.
> ci: install terraform before running generate

- argocd/resource_argocd_application_test.go
- argocd/schema_application.go
- argocd/structure_application.go
- argocd/utils.go
- docs/resources/application.md
- docs/resources/application_set.md
- internal/features/features.go
> Add support for Kustomize patches to `argocd_application`

- .github/workflows/release.yml
- .github/workflows/tests.yml
I tried to align the test/release file with the upstream https://github.com/hashicorp/terraform-provider-scaffolding-framework repo.
This changes the following:
- go installation is cached
- README.md changes don't trigger a testrun
- generate and build are two separate jobs that can run in parallel (but both block the acceptance_tests from running)
Relates to #440
> feat(tests): align workflow file with framework skaffold repo

- .github/workflows/tests.yml
Currently we use the "latest" terraform binary available in the Github runner. This is unpredictable and causes tests to suddenly be unstable if Terraform changes something from one minor version to another (as they likely did from 1.3 to 1.4, read https://github.com/runatlantis/atlantis/issues/2242).
Currently we only test one Terraform version. This change keeps this behavior but allows for multiple version testing in the future, in case we want this.
> feat: use pinned terraform versions in testing matrix

- .github/workflows/codeql-analysis.yml
- .github/workflows/release.yml
- .github/workflows/stale.yml
- .github/workflows/tests.yml
That broke our CI tests in the past, so we want this to be pinned and let dependabot suggest an update if available.
22.04 -> 24.04: https://github.blog/changelog/2024-11-05-notice-of-breaking-changes-for-github-actions/ & https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
Example of broken CI due to using latest: https://github.com/argoproj-labs/terraform-provider-argocd/pull/531
> feat: pin github hosted runner image

- .github/workflows/tests.yml
scaffolding repo does this: https://github.com/hashicorp/terraform-provider-scaffolding-framework/blob/main/.github/workflows/test.yml#L81C5-L81C29
Helps separating some logs from the test logs due to being another step.
> ci: Separate go mod download from acc test step

- .devcontainer.json
- argocd/resource_argocd_cluster_test.go
- argocd/schema_application_test.go
- argocd/schema_project_test.go
- go.mod
- tools/go.mod
This updates the used go version to `1.24`, matching the go version used in Argo CD and dependencies (example would be #575).
Our CI will pick the new version automatically since it reads `go.mod`. 
Closes #582
> feat: update to go 1.24

- .goreleaser.yml
Closes #583
https://goreleaser.com/deprecations/#archivesformat
> fix: goreleaser deprecated config fields

- go.mod
Alternative to #592 proofing that the library is not needed anywhere and kept in the go.mod file due to a `replace` directive, thus `go mod tidy` won't remove it.
```console
$ grep -R "remyoudompheng/bigfft"     
```
> feat: remove remyoudompheng/bigfft lib

- go.mod
Alternative to #591  proofing that the library is not needed anywhere and kept in the go.mod file due to a `replace` directive, thus `go mod tidy` won't remove it.
```console
$ grep -R "go-check/check"     
```
> feat: remove go-check/check lib

- argocd/structure_application.go
Fixes #492
The [reproduce-snippet](https://github.com/argoproj-labs/terraform-provider-argocd/issues/492#issuecomment-2495541373) I posted in the issue passed an object down into the code but eventually turned out to be `interface{} nil` causing a type-conversion panic because the second type-conversion isn't catched.
This fixes it by checking if the type-conversion worked, similar to the first one before proceeding.
For the reproduce-snippet that means the labels aren't applied at all because this for_each loop in itself seems incorrect.
No changes for everyone using the field like so:
```hcl
sync_policy {
managed_namespace_metadata {
labels = {
foo = "bar"
}
}
}
```
This getts applied correctly.
> Skip managed_namespace_metadata if type-conversion fails due to nil

- argocd/resource_argocd_repository.go
Fixes #597 
The repo can exist globally or within an AppProject, therefore read/delete operations should specify the AppProject in the `RepoQuery`. 
If the project is empty the field turns into an empty string which is interpreted as "global" by Argo CD.
> fix(repository): specify AppProject for read/delete operations

- .devcontainer.json
It takes even longer to create the container and is mostly not directly needed after setup.
> chore(devcontainer): don't setup the test env on container startup

- CONTRIBUTING.md
- README.md
I think the compatibility promise needs to be clarified, thus I reworded it.
In the contributor docs I tried to write down our handling of dependencies, so that it's obvious for contributors why we use which version of specific dependencies.
Oh and since the provider-move to a new location is now a few months old I moved the upgrade section down a bit in the README.
Closes #440 and #612
> docs: add explanation about our dependency management + clarify version compatiblity in README

- .github/workflows/tests.yml
- .golangci.yml
- argocd/resource_argocd_cluster_test.go
- argocd/structure_application.go
- argocd/structure_application_set.go
- argocd/structure_cluster.go
- argocd/structure_repository_certificate.go
Migrates golangci-lint to v2.
Most of the config was migrated using `golangci-lint migrate`, some excludes have been added manually to keep the PR small.
I tried fixing the `SA1019` issue in `internal/types/pgp_public_key.go` but gave up after half an hour due to the complexity that came with it. Might be something we need to address in a separate issue.
> chore(golangci-lint): migrate to v2

- argocd/resource_argocd_application.go
- argocd/schema_application.go
- argocd/schema_application_set.go
- argocd/schema_cluster.go
- argocd/schema_metadata.go
- argocd/validators.go
- argocd/validators_test.go
`validateMetadataLabels` ensures that labels are in a certain format. This works fine in most cases, except when this is used within appsets, which allow for labels to be templated. This adds a layer of indirection allowing for templated labels to be used, but only when an appset makes use of this feature.
> fix: allow templated label values

- argocd/resource_argocd_application_set.go
- argocd/resource_argocd_application_set_test.go
- manifests/install/cluster-rbac.yml
- manifests/install/patches/argocd-cmd-params-cm.yml
The pull request addressing issue [#548](https://github.com/argoproj-labs/terraform-provider-argocd/issues/548) enhances the Terraform ArgoCD provider by enabling support for ApplicationSets across any namespace. This update allows users to manage ApplicationSets beyond the default argocd namespace.
> feat: Support ApplicationSets in any Namespace

- argocd/resource_argocd_application_set.go
- argocd/resource_argocd_application_set_test.go
- argocd/schema_application_set.go
Adds a state migration to automatically update existing resources to use the new ID format. This should complete #548 and allow for a non-breaking change.
Most of the code was copied from #212
> feat(appsets): add state upgrade logic for appsets in any namespace

- GNUmakefile
- argocd/resource_argocd_cluster_test.go
- argocd/resource_argocd_repository_certificate_test.go
In the various `Makefile` tasks, add an option to filter out tests if necessary. I also fixed a few tests which were failing when running unit tests where the config params require a k8s environment to be up and running.
> chore: add ability to optionally filter tests

- internal/testhelpers/testcontainers.go
While running this locally I got a few tests that were persistently failing. It turned out to be because pulling the argocd image was slow, timing out the test init. Now we ensure that the image is pulled before performing `kubectl wait`, so that we only need to wait for the pods to be ready.
> chore: preload argocd before running testcontainer tests

- internal/provider/resource_repository.go
- internal/provider/resource_repository_test.go
Fixes #710. While migrating from an older version using sdkv2 to terraform-plugin-framework may need to recalculate the computed attributes, it should definitely not deadlock in the meantime.
Added a test where we create a repository using `7.8.0`, and then update it using the current version of this provider. Whereas before this deadlocked, it now updates as intended, and once this initial migration update has been done there is no state diff afterwards.
> fix: prevent deadlock

- .devcontainer.json
- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/PULL_REQUEST_TEMPLATE.MD
- .goreleaser.yml
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- RELEASE.md
- SECURITY.md
This PR:
- updates devcontainer config to only contain the minimal requirements
- aligns issue templates to be a bit more consistent
- disables opening issues without an issue template
- updates the contributing guide to reflect current state of development
- adds the slack channel as option when opening a new issue
- autopublishes github releases from within goreleaser (Terraform picks up the tag, so no need to wait with the Github release)
- Adds a simple PR template
- Adds a Code of Conduct and links to the CCNF CoC
- Adds a security policy for vulnerability reporting
- Adds a releasing process documentation
I know it's a lot of changes for one PR, but I thought it's better than having to review a bunch of PRs with very small changes.
> feat: refine & update community standards

- .github/workflows/codeql-analysis.yml
replaces the CodeQL workflow from 4 years ago with the template Github spits out currently.
Keeps schedule and pinned actions. Rest is default config.
> ci: replace codeql workflow with current github recommendation

- .github/workflows/codeql-analysis.yml
Builds the provider and tests to binaries that CodeQL can analyze, raises coverage from 71% to 99%.
Still missing the `tools/tools.go` file.
> ci: build provider and tests for codeql analysis

- CONTRIBUTING.md
Adds a simple checklist to the contribution guide with the most important facts.
/kind documentation
> docs: add contributing checklist
