argoproj-labs/terraform-provider-argocd

- GNUmakefile
- argocd/resource_argocd_project_token.go
- argocd/resource_argocd_project_token_test.go
- go.sum
> Handle simultaneous token creations within the same project role

- README.md
- argocd/features.go
- argocd/features_test.go
- argocd/provider.go
- argocd/provider_test.go
- argocd/resource_argocd_project.go
- argocd/resource_argocd_project_test.go
- argocd/resource_argocd_project_token.go
- argocd/resource_argocd_project_token_test.go
- argocd/structure_metadata.go
- argocd/structure_project.go
- argocd/structures.go
- argocd/utils.go
- argocd/validators.go
- main.go
> enhanced token validation

- .github/workflows/release.yml
- .github/workflows/tests.yml
> Automated Github releases

- README.md
- argocd/features.go
- argocd/provider.go
- argocd/resource_argocd_repository.go
- argocd/resource_argocd_repository_test.go
- argocd/schema_repository.go
- argocd/structure_project.go
- argocd/structure_repository.go
> Adds argocd_repository resource

- argocd/features.go
- argocd/provider.go
- argocd/resource_argocd_application.go
- argocd/resource_argocd_project.go
- argocd/resource_argocd_project_token.go
- argocd/resource_argocd_repository.go
- argocd/utils.go
- manifests/install/install.yml
- scripts/testacc_prepare_env.sh
> Shared api service clients across resources

- argocd/features.go
- argocd/provider.go
- argocd/resource_argocd_repository_credentials.go
- argocd/resource_argocd_repository_credentials_test.go
- argocd/schema_repository_credentials.go
- argocd/structure_repository.go
- argocd/structure_repository_credentials.go
- argocd/utils.go
> adds argocd_repository_credentials resource

- README.md
- argocd/provider.go
- argocd/resource_argocd_project.go
- argocd/resource_argocd_project_token.go
- argocd/resource_argocd_repository.go
- argocd/resource_argocd_repository_credentials.go
- argocd/resource_argocd_repository_credentials_test.go
- argocd/resource_argocd_repository_test.go
- argocd/schema_repository.go
- argocd/structure_repository.go
- manifests/install/git-private-repository.yml
> Handle concurrent mass modification of repository and repository_credentials resources

- .github/workflows/release.yml
- .goreleaser.yml
- README.md
- docs/index.md
- docs/resources/project.md
- docs/resources/token.md
Adds Terraform registry compatible docs and release workflow.
> Support for terraform registry

- docs/resources/application.md
- docs/resources/project.md
- docs/resources/repository.md
- docs/resources/repository_credentials.md
> document imports

- argocd/features_test.go
- argocd/resource_argocd_project.go
- go.mod
- go.sum
> fix project deletion panics

- argocd/resource_argocd_application_test.go
- argocd/schema_application.go
- argocd/structure_application.go
- argocd/utils.go
- docs/resources/application.md
> argocd_application: added retry configuration block to sync policy

- argocd/resource_argocd_application_test.go
- argocd/schema_application.go
- argocd/schema_project.go
- argocd/structure_application.go
- docs/resources/application.md
- docs/resources/project.md
> argocd_application: support for kustomize.common_annotations and sync_policy.automated.allow_empty

- argocd/resource_argocd_project.go
> argocd_project: fix roles updates for newly added roles (#51)

- argocd/resource_argocd_project.go
- argocd/schema_project.go
- argocd/schema_project_test.go
> argocd_project: introduce schema versioning and migration

- argocd/structure_cluster.go
Fixes issue described in https://github.com/oboukili/terraform-provider-argocd/issues/37#issuecomment-785089848
> fix aws auth config

- argocd/structure_cluster.go
> fix: cluster state failed to save after being applied

- README.md
- argocd/features.go
- argocd/features_test.go
- argocd/provider.go
- argocd/resource_argocd_cluster.go
- argocd/resource_argocd_cluster_test.go
- argocd/schema_cluster.go
- argocd/structure_application.go
- argocd/structure_cluster.go
- argocd/utils.go
- docs/resources/cluster.md
- docs/resources/repository.md
- go.mod
- go.sum
- scripts/testacc_prepare_env.sh
> add an argocd_cluster resource

- .goreleaser.yml
> support for Darwin Arm64 (M1) builds

- docs/resources/cluster.md
The workaround was described in https://github.com/oboukili/terraform-provider-argocd/issues/106
As this basically mimics the [ArgoCD CLI behaviour](https://github.com/argoproj/argo-cd/blob/70a08a0aa6cde6bcdd5a6ce4140d87c40a3fa25e/util/clusterauth/clusterauth.go#L176).
Thx  @davidedmonds
> docs(cluster): Describe GKE cluster workaround

- go.mod
- go.sum
See https://github.com/gruntwork-io/terratest/pull/1039
Signed-off-by: Raphaël Pinson <raphael.pinson@camptocamp.com>
> fix(tests): update go-cty and terraform-json

- argocd/resource_argocd_application.go
Signed-off-by: Raphaël Pinson <raphael.pinson@camptocamp.com>
> feat(application): add cascade parameter

- argocd/schema_cluster.go
Should hopefully fix https://github.com/oboukili/terraform-provider-argocd/issues/80
> Fix exec_provider_config args and env schemas

- argocd/provider.go
> fix: extend authentication to other cloud providers

- argocd/resource_argocd_project.go
- argocd/resource_argocd_project_test.go
> fix: crash when adding a role on an existing project without role

- argocd/resource_argocd_application_test.go
- argocd/structure_application.go
Fixes crashes on empty sync_policy-related blocks & wrong defaults values
#81 #94 #152
> fix(application): prevent crash on empty sync_policy/automated block

- docs/resources/cluster.md
Following discussions at #158, clarify & add more documentation examples
> docs: more examples for ca_data argocd_cluster.tls_client_config

- argocd/resource_argocd_application_test.go
- argocd/schema_application.go
- argocd/structure_application.go
> fix: handle recurse drift with DiffSuppressFunc

- argocd/resource_argocd_application_test.go
- argocd/structure_application.go
> fix: crash when using argocd_application.spec.info

- argocd/provider.go
- argocd/resource_argocd_application_test.go
- argocd/resource_argocd_cluster_test.go
> fix: crash when using provider headers

- argocd/schema_repository.go
- argocd/schema_repository_credentials.go
- argocd/structure_repository.go
- argocd/structure_repository_credentials.go
- docs/resources/repository.md
- docs/resources/repository_credentials.md
This PR adds the option to specify the parameter `enableOCI`.
> Add option to pass enableOCI

- argocd/features.go
- argocd/provider_test.go
- argocd/resource_argocd_repository.go
- argocd/resource_argocd_repository_test.go
- argocd/schema_repository.go
- argocd/schema_repository_credentials.go
- argocd/structure_repository.go
- docs/resources/repository.md
Cherry-picked @felipem1210 commits from #189 (thanks for initial work !)
* added feature checks (repository project available since v2.2.0)
* added tests
Resolves #183
> feat: add support for add project scoped repositories

- .gitignore
- manifests/local-dev/.gitignore
- manifests/local-dev/application.tf
- manifests/local-dev/cluster.tf
- manifests/local-dev/project-token.tf
- manifests/local-dev/project.tf
- manifests/local-dev/repository-credentials.tf
- manifests/local-dev/repository.tf
- manifests/local-dev/versions.tf
Makes life a bit easier when trying to reproduce/debug issues as one can run `terraform` against the local environment whilst debugging the provider.
> Add all resources to `local-dev` Terraform code

- argocd/resource_argocd_cluster.go
- argocd/resource_argocd_repository.go
- argocd/resource_argocd_repository_credentials.go
- argocd/resource_argocd_repository_credentials_test.go
- argocd/schema_repository_credentials.go
Fixes #242 (and potentially similar issues on `argocd_cluster` and `argocd_repository` resources - see comment in https://github.com/oboukili/terraform-provider-argocd/commit/c848ce31e0a6ed2cfc6951aaa837a36c66b3f857). 
Related to #84
> Fix error `inconsistent result after apply` on `argocd_repository_credentials`

- argocd/resource_argocd_application_test.go
- argocd/schema_application.go
- argocd/structure_application.go
- docs/resources/application.md
> Add support for `jsonnet` libraries

- argocd/resource_argocd_application_test.go
- argocd/schema_application.go
- docs/resources/application.md
> Mark `spec.destination.namespace` as optional on ArgoCD application

- argocd/resource_argocd_application_test.go
- argocd/schema_application.go
- argocd/structure_application.go
- docs/resources/application.md
- docs/resources/application_set.md
quick PR to add support for `ignoreMissingValueFiles` based on this issue: #287
> Add support for `ignoreMissingValueFiles` helm application parameter

- argocd/resource_argocd_application_test.go
- argocd/schema_application.go
- argocd/structure_application.go
- docs/resources/application.md
- docs/resources/application_set.md
While handling #292 I remembered this old issue and figured we may as well deal with it at the same time...
Closes #195
> Add support for Helm file parameters

- argocd/resource_argocd_application.go
- argocd/resource_argocd_application_test.go
- argocd/schema_application.go
- argocd/structure_application.go
- docs/resources/application.md
- docs/resources/application_set.md
- internal/features/features.go
> Add support for managed namespace metadata in `argocd_application`

- argocd/resource_argocd_application.go
- argocd/resource_argocd_application_test.go
- argocd/schema_application.go
- argocd/structure_application.go
- docs/resources/application.md
- manifests/local-dev/outputs.tf
Partial resolution of #155 
Closes #234
Note: unfortunately, due to a known [issue](https://github.com/hashicorp/terraform-plugin-docs/issues/66) with generating docs on nested, computed attributes, the resulting documentation contains no description :disappointed: This can be resolved by [migrating from the provider SDKv2 to the plugin framework](https://developer.hashicorp.com/terraform/plugin/framework/migrating) although that's a whole project in itself :grimacing:
> Add read-only `status` attribute to `argocd_application`

- docs/resources/cluster.md
- examples/resources/argocd_cluster/resource.tf
> docs: fix EKS `argocd_cluster` example

- docs/resources/application_set.md
- examples/resources/argocd_application_set/resource.tf
> docs: fix example for application set list generator

- argocd/structure_application_set.go
> fix(argocd_application_set): ensure `sync` sync policy is correctly set  

- .github/workflows/codeql-analysis.yml
- .github/workflows/tests.yml
Motivation:
- [Inclusive Naming Initiative > Tier 1: Replace Immediately](https://inclusivenaming.org/word-lists/tier-1/)
- https://www.cncf.io/announcements/2021/10/13/inclusive-naming-initiative-announces-new-community-resources-for-a-more-inclusive-future/
> chore: Prepare for "main" branch

- .github/workflows/codeql-analysis.yml
PR
- #425
will take care to update the hard-pinned actions.
> chore: Update CodeQL workflow

- .github/CODEOWNERS
Add CODEOWNERS file to automatically request reviews of the PRs.
> docs: Add CODEOWNERS

- .github/workflows/tests.yml
- scripts/testacc_prepare_env.sh
> feat: test against argo-cd 2.11

- main.go
> feat: rename source advertised in plugin server

- .github/workflows/tests.yml
Credits:
https://github.com/openedx/edx-platform/blob/e286d78a295cb5fc8e2ecb1fa10735fdc2b93d3e/.github/workflows/pylint-checks.yml#L70-L84
We can then use it for the branch protection to ensure all matrix tests against all Argo CD versions pass.
> ci: Add job which aggregates test results used for branch protection

- docs/index.md
- templates/index.md.tmpl
> docs: add hint about plain_text

- argocd/resource_argocd_application_set_test.go
- argocd/structure_application_set.go
#624 added support for plugin generators, but the support for it was never added to the nested generators.
> fix: add plugin generator to nested generator

- argocd/resource_argocd_application_set_test.go
- argocd/resource_argocd_application_test.go
- internal/provider/data_source_application_test.go
- manifests/local-dev/application-set.tf
Fixes #649 
Related to:
- https://github.com/argoproj/argocd-example-apps/pull/385
> ci: Update outdated external testing deps

- argocd/resource_argocd_application.go
- argocd/resource_argocd_application_set.go
- argocd/resource_argocd_application_test.go
- argocd/schema_application.go
- argocd/structure_application.go
- argocd/structure_application_set.go
- docs/data-sources/application.md
- docs/resources/application.md
- internal/features/features.go
- internal/provider/model_application.go
- templates/data-sources/application.md.tmpl
- templates/resources/application.md.tmpl
Hello,
This PR related to https://github.com/argoproj/argo-cd/pull/20470 to add name field in the application source object.
Impacted component will be `argocd_application` resource & data source.
Let me know if I missed something. thanks
> Feat: Support for Application Source Name

- .github/workflows/tests.yml
**What type of PR is this?**
[//]: # (Uncomment only one  line, and delete the rest.)
[//]: # (For example,  would simply become: /kind bug  )
/kind dependency
**What does this PR do / why we need it**:
Updates Terraform to 1.13 to ensure we test/build against the current version of Terraform
**Have you updated the necessary documentation?**
**Which issue(s) this PR fixes**:
Fixes #?
**How to test changes / Special notes to the reviewer**:
> ci: update used terraform version to 1.13

- .github/workflows/release.yml
Adds a missing `#` char to the release step
> ci(release): add missing comment char
